---
- hosts: all
  become: true
  pre_tasks:
    - name: Check hostname is correct
      debug: msg="{{ ansible_hostname|lower }} equals {{ inventory_hostname }}"
      failed_when: "ansible_hostname|lower != inventory_hostname"
  tasks:
    - name: Reset the monuser password
      user:
        name: "monuser"
        update_password: always
        password: "{{ ***********|password_hash('sha512') }}"
