---
- name: Check sudo user in server.
  hosts: test8
  tasks:
     #command:  hostname
     #command: for u in $(awk -F'[/:]' '{if($3>=1000&&$3!=65534) print $1}' /etc/passwd); do sudo -lU "$u" ; done
   - shell: getent passwd | cut -f1 -d: | sudo xargs -L1 sudo -l -U | grep -v 'not allowed'
     register: ps
   - debug: var=ps.stdout.lines
