---
- name: usersdeletion 
  hosts: test8
  include_vars:
  file: users
  tasks:
  - user:
      name: "{{users}}"
      state: absent
      remove: yes
#  tasks:
#  - name: 
#    user:
#     name: "{{ item }}"
#     state: absent
#     remove: yes
#    loop:
#     - test1
#     - test2
#     - test3
#     - test4
#     - test5
#
