---
- name:
  hosts:  all
  ignore_errors: yes
  tasks:
    - name:
      get_url:
       url: ftp://192.168.80.166/hwreport.empty
       dest: /root/hwreport.txt
    - name:
      replace:
        regexp: "{{item.src}}"
        replace: "{{item.dest}}"
        dest: /root/hwreport.txt
      loop:
        - src: "hostname"
          dest: "{{ansible_hostname}}"
        
