---
- name:
  hosts: servera
  tasks:
    - name: Removing duplicate line if exist in /etc/rsyslog.conf
      lineinfile:
        dest: /root/test
        backup: no
        regexp: "{{item}}" 
        state: absent
      loop:
       - "/var/log/secure"
       - "The authpriv file has restricted access"
       - "# Set permissions and group ownership of /var/log/secure so splunk can read"
       - "FileCreateMode 0640"
       - "FileGroup splunk"
       - "# Set permissions and group ownership back to default"
       - "FileCreateMode 0600"
       - "FileGroup root"
    
    - name: Grant group owner permissions to /var/log/sec
      shell: "chown root:splunk /var/log/secure; chmod 0640 /var/log/secure"
      args:
       warn: false

    - name: Now inserting the required line in /etc/rsyslog.conf
      blockinfile:
        path: /root/test
        insertafter: 'local7.*'
        state: present
        backup: yes
        content: |
         # Set permissions and group ownership of /var/log/secure so splunk can read 
         $FileCreateMode 0640
         $FileGroup splunk
         
         # The authpriv file has restricted access. 
         authpriv.*                                              /var/log/secure 
          
         # Set permissions and group ownership back to default 
         $FileCreateMode 0600
         $FileGroup root
    - name: Restart the rsyslog and splunk service
      service:
        name: "{{item}}"
        state: restarted
      loop:
        - rsyslog
        - chronyd

